### ISSUE TITLE
Devliver vs Payment / Atomic Swaps

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#14]
The docs are silent on how long each party to a transaction may be forced to wait until the transaction is complete. I'd like to see some information about the expected settlement delay of the network.

The docs are silent on the timing (wall clock time) of the different steps. After the 'buyer' signs the 'exchange offer' and returns it to the seller waiting for him to sign and pass to the network for settlement then he is at risk. He has committed to exchange A for B so cannot sell A to another party but has not yet received B. In fact the seller may decided to not complete the transaction and not pass to the network for settlement, he may hold the signed offer waiting for a favourable time until he chooses to sign and pass for settlement. If protocol enforced some time limit the docs should mention this. If the protocol does not enforce limits them it should.

It should follow something like this:
X asks Y for a price for A in terms of B
Y provides price with a time (Z) at which the price will expire
X confirms (before time Z) that it would like to buy A in exchange for B from Y to be settled by time Z^
Y checks that the response from X is before time Z and if so passed the settlement to the network before time Z^

So all parties know the time that prices are live for and the time by which, with certainty, an exchange will be completed or will have failed.

**Comment by eamesyi** [comment]
The transfer action has an 'OfferExpiry' field (timestamp) that users can define on each token transaction.  Neither contracting party has to sign anything without first being happy with the terms of the transfer (asset/price/qty), but also the OfferExpiry which limits their risk.

When OfferExpiry is set to 9:31 AM 29/08/2019, then that transfer action must be signed by both parties and broadcast to the network before that time otherwise the smart contract will reject it.  The first contracting party to sign the transaction will lock that value into place as the value is under the footprint of the signature.

The OfferExpiry could be set to anything and would depend on the nature of the deal and/or use case, but I expect it would be common to have values that give the other party approximately 8-48 hours, as well as seconds or minutes. 

This is documented in the Transfer action on the Actions page under Specification.
